// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ProtoResponseEntity.proto
// Protobuf Java Version: 4.31.0

package com.clmcat.framework.webmvc.protobuf.entity;

@com.google.protobuf.Generated
public final class ProtoResponseEntityOuterClass {
  private ProtoResponseEntityOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      ProtoResponseEntityOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoResponseEntity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoResponseEntity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ProtoResponseEntity.proto\"\212\002\n\023ProtoRes" +
      "ponseEntity\022\026\n\trequestId\030\001 \001(\tH\000\210\001\001\022\023\n\006s" +
      "tatus\030\002 \001(\005H\001\210\001\001\022\022\n\005state\030\003 \001(\tH\002\210\001\001\022\024\n\007" +
      "message\030\004 \001(\tH\003\210\001\001\022 \n\010dataType\030\005 \001(\0162\t.D" +
      "ataTypeH\004\210\001\001\022\021\n\004data\030\006 \001(\014H\005\210\001\001\022\025\n\010errpl" +
      "ace\030\007 \001(\tH\006\210\001\001B\014\n\n_requestIdB\t\n\007_statusB" +
      "\010\n\006_stateB\n\n\010_messageB\013\n\t_dataTypeB\007\n\005_d" +
      "ataB\013\n\t_errplace*3\n\010DataType\022\010\n\004NONE\020\000\022\014" +
      "\n\010PROTOBUF\020\001\022\017\n\013JSON_STRING\020\002B+\n\'org.ns." +
      "framework.webmvc.protobuf.entityP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ProtoResponseEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtoResponseEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtoResponseEntity_descriptor,
        new java.lang.String[] { "RequestId", "Status", "State", "Message", "DataType", "Data", "Errplace", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
