// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ProtoResponseEntity.proto
// Protobuf Java Version: 4.31.0

package com.clmcat.framework.webmvc.protobuf.entity;

@com.google.protobuf.Generated
public interface ProtoResponseEntityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoResponseEntity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string requestId = 1;</code>
   * @return Whether the requestId field is set.
   */
  boolean hasRequestId();
  /**
   * <code>optional string requestId = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>optional string requestId = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>optional int32 status = 2;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>optional int32 status = 2;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>optional string state = 3;</code>
   * @return Whether the state field is set.
   */
  boolean hasState();
  /**
   * <code>optional string state = 3;</code>
   * @return The state.
   */
  java.lang.String getState();
  /**
   * <code>optional string state = 3;</code>
   * @return The bytes for state.
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>optional string message = 4;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>optional string message = 4;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 4;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>optional .DataType dataType = 5;</code>
   * @return Whether the dataType field is set.
   */
  boolean hasDataType();
  /**
   * <code>optional .DataType dataType = 5;</code>
   * @return The enum numeric value on the wire for dataType.
   */
  int getDataTypeValue();
  /**
   * <code>optional .DataType dataType = 5;</code>
   * @return The dataType.
   */
  DataType getDataType();

  /**
   * <code>optional bytes data = 6;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>optional bytes data = 6;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>optional string errplace = 7;</code>
   * @return Whether the errplace field is set.
   */
  boolean hasErrplace();
  /**
   * <code>optional string errplace = 7;</code>
   * @return The errplace.
   */
  java.lang.String getErrplace();
  /**
   * <code>optional string errplace = 7;</code>
   * @return The bytes for errplace.
   */
  com.google.protobuf.ByteString
      getErrplaceBytes();
}
