<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>clmcat-international</artifactId>
    <parent>
        <groupId>com.clmcat.framework</groupId>
        <artifactId>clmcat-framework</artifactId>
        <version>1.1.0</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>com.clmcat.framework</groupId>
            <artifactId>clmcat-webmvc</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
        </dependency>
    </dependencies>
</project>